# Setup
title: Bob's Burgers Butts Tracker
tagline: Spreading the joy, one cheek at a time
url: https://bobsburgersbutts.lol
paginate: 1
baseurl: ""
permalink: pretty

defaults:
  - scope:
      path: "assets/danny"
    values:
      image: true

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Specify the author for blog posts
author:
  name: The Peanut Gallery ðŸ¥œ

description: "We used software that's typically reserved for professionals to bring you the best Bob's Burger Butt tracker around."
